# Generated by Django 4.0.1 on 2022-01-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('intro', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['createdAt'],
            },
        ),
    ]
