# Generated by Django 4.0.1 on 2022-01-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
