# Generated by Django 4.0.1 on 2022-01-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
